# Copyright (c) 2024 Espresso Systems (espressosys.com)
# This file is part of the HotShot Builder Protocol.
#
# TODO: License

[meta]
NAME = "hs-builder"
DESCRIPTION = ""
FORMAT_VERSION = "0.1.0"

[route.available_blocks]
PATH = ["availableblocks/:parent_hash"]
":parent_hash" = "TaggedBase64"
DOC = """
Get descriptions for all block candidates based on a specific parent block.

Returns
```
[
    "block_metadata": {
        "block_hash":  TaggedBase64,
        "block_size":  integer,
        "offered_fee": integer,
    },
]
```
"""

[route.claim_block]
PATH = ["claimblock/:block_hash/:signature"]
":block_hash" = "TaggedBase64"
":signature" = "TaggedBase64"
DOC = """
Get the specified block candidate.

Returns application-specific encoded transactions type
"""

[route.submit_txn]
PATH = ["submittxn/:txn"]
":txn" = "TaggedBase64"
DOC = """

Returns ---
"""
